#tomcat端口
server:
  port: 8761
  tomcat:
    uri-encoding: UTF-8

#应用名    
spring:
  application:
    name: eureka-server
 
#权限认证   
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456

#eureka注册与发现配置  
eureka:
  environment: product
  datacenter: tramp
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:123456@localhost:8762/eureka,http://user:123456@localhost:8763/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
      